### ISSUE TITLE
RuntimeError: expected scalar type Long but found Float

### ISSUE THREAD

**Issue by ShengyuH** [yanx27/JS3C-Net#3]
hi Xu Yan,

I got a problem when evaluating segmantic segmentation on kitti dataset. It reports:
```
Restore from log/JS3C-Net-kitti/model_segiou_0.6327_compltiou_0.2350_epoch79.pth
#classifer parameters 4843953
[IOU EVAL] IGNORE:  []
[IOU EVAL] INCLUDE:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
  0%|                                                                                                            | 0/4071 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "test_kitti_segment.py", line 193, in <module>
    predictions = classifier(batch)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "test_kitti_segment.py", line 74, in forward
    seg_output, _ = self.seg_head(x)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch2/shengyu/JS3C-Net/models/SubSparseConv.py", line 41, in forward
    x = self.sparseModel(batch_x)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch2/shengyu/JS3C-Net/lib/sparseconvnet/tables.py", line 48, in forward
    return [module(input) for module in self._modules.values()]
  File "/scratch2/shengyu/JS3C-Net/lib/sparseconvnet/tables.py", line 48, in <listcomp>
    return [module(input) for module in self._modules.values()]
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/scratch2/shengyu/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch2/shengyu/JS3C-Net/lib/sparseconvnet/convolution.py", line 39, in forward
    output.features = ConvolutionFunction.apply(
  File "/scratch2/shengyu/JS3C-Net/lib/sparseconvnet/convolution.py", line 95, in forward
    sparseconvnet.SCN.Convolution_updateOutput(
RuntimeError: expected scalar type Long but found Float
```

I am now using Ubuntu 20.04, CUDA 11.2, gcc 9.3.0.  python 3.8.5. I can compile spconv under ```lib/spconv``` by running 
```
python setup.py bdist_wheel
```
without any issues. When compiling sparseconvnet I have to change ```c++11``` to ```c++14``` in ```lib/setup.py``` and ```lib/nearest_neighbors/setup.py```. 
I came across the above-mentioned issues after having everything compiled.  I checked the input here: https://github.com/yanx27/JS3C-Net/blob/c4eed02b2febc118b31c074a9f1d6321ad1c04be/models/SubSparseConv.py#L41
x['seg_coords'] are int64 tensors and x['seg_features'] are float32 tensors. 

Do you have any clues of this problem? 

Best,
Shengyu

**Comment by yanx27** [comment]
@ShengyuH Hi, thanks for your attention. We don't have extensive experiments on CUDA 11.2. According to my experience, the input of the model should be followed by these types, x['seg_coords'] are Long and x['seg_features'] are float. Did you check it?

**Comment by ShengyuH** [comment]
@yanx27  hi yes i checked that
```
-> x = self.sparseModel(batch_x)
(Pdb) batch_x[0].dtype
torch.int64
(Pdb) batch_x[1].dtype
torch.float32
```
They seem to be of correct data types. I am using``` torch==1.8.0.dev20201124+cu110```.

**Comment by yanx27** [comment]
@ShengyuH Currently, I have not idea for this issue. You can try this code with lower version CUDA. Also, if you fix this bug, welcome to share your experience :)

**Comment by Yan-Xia** [comment]
Hi, did you solve this issue? I'm also meet this problem.

**Comment by Yan-Xia** [comment]
Hi, did you solve this issue? I'm also meet this problem.

**Comment by Gao-JT** [comment]
@ShengyuH @Yan-Xia 
Hello, thanks for your attention. I think this may be caused by the unsuccessful compilation of SparseconvNet(https://github.com/facebookresearch/SparseConvNet). I suggest you try to run SparseConvNet's **Hello World demo**  (https://github.com/facebookresearch/SparseConvNet#hello-world) in your existing environment.

**Comment by zoomin-lee** [comment]
Hi, did you solve this issue?

**Comment by LeopoldACC** [comment]
> @ShengyuH @Yan-Xia Hello, thanks for your attention. I think this may be caused by the unsuccessful compilation of SparseconvNet(https://github.com/facebookresearch/SparseConvNet). I suggest you try to run SparseConvNet's **Hello World demo** (https://github.com/facebookresearch/SparseConvNet#hello-world) in your existing environment.

hi @Gao-JT ，I meet the same error as shown in https://github.com/yanx27/JS3C-Net/issues/19. With your suggestion,I run the demo to check whether successfully compiled of SparseconvNet, it seems that failed.
```
Input SparseConvNetTensor: SparseConvNetTensor<<features=tensor([[1.],
        [1.],                                        
        [1.],                                                                                        
        [1.],                              
        [1.],                          
        [1.],                                   
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],                                                                       
        [1.],                                                                                        
        [1.],        
        [1.],                                                                                        
        [1.],                                                                    
        [1.],                                                                              
        [1.],                                                                             
        [1.],                                                                                        
        [1.],                                                         
        [1.],                                        
        [1.],                                                                                        
        [1.],                              
        [1.],                          
        [1.],                                   
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],                                                                       
        [1.],                                                                                        
        [1.],        
        [1.],                                                                                        
        [1.],                                                                    
        [1.],                                                                              
        [1.],                                                                             
        [1.],                                                                                        
        [1.],                                                         
        [1.],                                        
        [1.],                                                                                        
        [1.],                              
        [1.],                          
        [1.],                                   
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],                                                                       
        [1.]], device='cuda:0'),features.shape=torch.Size([132, 1]),batch_locations=tensor([[ 0,  1,  0],
        [ 0,  5,  0],
        [ 0,  8,  0],                                                                                         
        [ 0,  9,  0],                                                            
        [ 0, 10,  0],                                                                      
        [ 0, 13,  0],                                                                     
        [ 0, 18,  0],                                                                                      
        [ 0, 23,  0],                                                 
        [ 0, 24,  0],                                
        [ 0, 30,  0],                                                                                         
        [ 0, 38,  0],                      
        [ 0, 42,  0],                  
        [ 0, 43,  0],                           
        [ 0, 47,  0],
        [ 0, 48,  0],
        [ 0, 49,  0],
        [ 0, 53,  0],
        [ 0, 58,  0],
        [ 0, 59,  0],
        [ 0, 60,  0],
        [ 1,  1,  0],
        [ 1,  5,  0],
        [ 1,  8,  0],
        [ 1, 13,  0],
        [ 1, 18,  0],
        [ 1, 22,  0],
        [ 1, 25,  0],
        [ 1, 30,  0],
        [ 1, 38,  0],
        [ 1, 41,  0],
        [ 1, 44,  0],
        [ 1, 47,  0],
        [ 1, 50,  0],
        [ 1, 53,  0],
        [ 1, 58,  0],
        [ 1, 61,  0],
        [ 2,  1,  0],
        [ 2,  2,  0],
        [ 2,  3,  0],
        [ 2,  4,  0],
        [ 2,  5,  0],
        [ 2,  8,  0],
        [ 2,  9,  0],
        [ 2, 13,  0],
        [ 2, 18,  0],
        [ 2, 22,  0],                                                 
        [ 2, 25,  0],                                                 
        [ 2, 30,  0],
        [ 2, 34,  0],                                                 
        [ 2, 38,  0],                                                 
        [ 2, 41,  0],                                                 
        [ 2, 44,  0],                                                 
        [ 2, 47,  0],                                                 
        [ 2, 48,  0],                                                 
        [ 2, 49,  0],                                
        [ 2, 53,  0],                                                 
        [ 2, 58,  0],                      
        [ 2, 62,  0],                  
        [ 3,  1,  0],                           
        [ 3,  5,  0],
        [ 3,  8,  0],
        [ 3, 13,  0],
        [ 3, 18,  0],
        [ 3, 22,  0],
        [ 3, 25,  0],
        [ 3, 31,  0],
        [ 3, 33,  0],
        [ 3, 35,  0],
        [ 3, 37,  0],
        [ 3, 41,  0],
        [ 3, 44,  0],
        [ 3, 47,  0],
        [ 3, 50,  0],
        [ 3, 53,  0],
        [ 3, 58,  0],
        [ 3, 61,  0],
        [ 4,  1,  0],
        [ 4,  5,  0],
        [ 4,  8,  0],
        [ 4,  9,  0],
        [ 4, 10,  0],
        [ 4, 13,  0],
        [ 4, 14,  0],
        [ 4, 15,  0],
        [ 4, 18,  0],
        [ 4, 19,  0],
        [ 4, 20,  0],
        [ 4, 23,  0],
        [ 4, 24,  0],
        [ 4, 32,  0],
        [ 4, 36,  0],
        [ 4, 42,  0],                                                               
        [ 4, 43,  0],                                                                                    
        [ 4, 47,  0],
        [ 4, 50,  0],                                                                                                
        [ 4, 53,  0],                                                            
        [ 4, 54,  0],                                                                      
        [ 4, 55,  0],                                                                     
        [ 4, 58,  0],                                                                                      
        [ 4, 59,  0],                                                 
        [ 4, 60,  0],                                
        [ 0,  1,  1],                                                                                              
        [ 0,  2,  1],                      
        [ 0,  3,  1],                  
        [ 0, 18,  1],                           
        [ 0, 19,  1],
        [ 0, 20,  1],
        [ 0, 21,  1],
        [ 0, 22,  1],
        [ 1,  1,  1],
        [ 1,  4,  1],
        [ 1,  7,  1],
        [ 1, 11,  1],
        [ 1, 12,  1],
        [ 1, 13,  1],
        [ 1, 21,  1],
        [ 2,  1,  1],
        [ 2,  2,  1],
        [ 2,  3,  1],
        [ 2, 20,  1],
        [ 3,  1,  1],
        [ 3,  7,  1],
        [ 3, 11,  1],
        [ 3, 12,  1],
        [ 3, 13,  1],
        [ 3, 21,  1],
        [ 4,  1,  1],
        [ 4,  7,  1],
        [ 4, 18,  1],
        [ 4, 19,  1],
        [ 4, 20,  1],
        [ 4, 21,  1]]),batch_locations.shape=torch.Size([132, 3]),spatial size=tensor([87, 87])>>
Traceback (most recent call last):
  File "test_sparseconvnet.py", line 51, in <module>
    output = model(input)
  File "/data/anaconda3/envs/occld/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/anaconda3/envs/occld/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/data/anaconda3/envs/occld/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/anaconda3/envs/occld/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/data/anaconda3/envs/occld/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/projects/JS3C-Net-main/lib/sparseconvnet/maxPooling.py", line 94, in forward       
    self.nFeaturesToDrop)         
  File "/data/projects/JS3C-Net-main/lib/sparseconvnet/maxPooling.py", line 38, in forward
    nFeaturesToDrop)     
RuntimeError: expected scalar type Long but found Float                                                            

```
