### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by hackerliang** [yanx27/JS3C-Net#8]
@yanx27 Thank you for sharing your code. But I have a problem and need your help. I want to visualize the segment pointcloud that output by your model, and I just use your pre-trained model file to output the pointcloud data(validation dataset)(semantic kitti sequence 08) by

```bash
python test_kitti_segment.py --log_dir JS3C-Net-kitti --gpu 0 --dataset val
```

Then I follow the instruction here by semantic kitti
https://github.com/PRBonn/semantic-kitti-api#visualization

```bash
./visualize.py --sequence 08 --dataset /home/user/JS3C-Net/log/JS3C-Net-kitti/dump/segmentation/submit_val2021_04_21 --predictions /home/user/JS3C-Net/log/JS3C-Net-kitti/dump/segmentation/submit_val2021_04_21
```

But I found that there's an error showing that the scan(velodyne) and label(predictions) don't contain the same number of points
```text
********************************************************************************
INTERFACE:
Dataset /home/user/JS3C-Net/log/JS3C-Net-kitti/dump/segmentation/submit_val2021_04_21
Config config/semantic-kitti.yaml
Sequence 08
Predictions /home/user/JS3C-Net/log/JS3C-Net-kitti/dump/segmentation/submit_val2021_04_21
ignore_semantics False
do_instances False
ignore_safety False
offset 0
********************************************************************************
Opening config file config/semantic-kitti.yaml
Sequence folder exists! Using sequence from /home/user/JS3C-Net/log/JS3C-Net-kitti/dump/segmentation/submit_val2021_04_21/sequences/08/velodyne
Labels folder exists! Using labels from /home/user/JS3C-Net/log/JS3C-Net-kitti/dump/segmentation/submit_val2021_04_21/sequences/08/predictions
Using semantics in visualizer
Using instances in visualizer
Points shape:  (123389, 3)
Label shape:  (116465,)
Traceback (most recent call last):
  File "./visualize.py", line 154, in <module>
    semantics=semantics, instances=instances and semantics)
  File "/home/user/semantic-kitti-api/auxiliary/laserscanvis.py", line 29, in __init__
    self.update_scan()
  File "/home/user/semantic-kitti-api/auxiliary/laserscanvis.py", line 132, in update_scan
    self.scan.open_label(self.label_names[self.offset])
  File "/home/user/semantic-kitti-api/auxiliary/laserscan.py", line 236, in open_label
    self.set_label(label)
  File "/home/user/semantic-kitti-api/auxiliary/laserscan.py", line 254, in set_label
    raise ValueError("Scan and Label don't contain same number of points")
ValueError: Scan and Label don't contain same number of points
```

My kitti dataset folder and prediction folder are shown as follow:

```text
/home/user/JS3C-Net/log/JS3C-Net-kitti/dump
└── segmentation
    └── submit_val2021_04_21
        └── sequences
            └── 08
                ├── calib.txt
                ├── labels
                │   ├── 000000.label
                │   ├── ...
                │   └── 004070.label
                ├── poses.txt
                ├── predictions
                │   ├── 000000.label
                │   ├── ...
                │   └── 004070.label
                ├── times.txt
                └── velodyne
                    ├── 000000.bin
                    ├── ...
                    └── 004070.bin
```

Best,
Liang

**Comment by yanx27** [comment]
Hi @hackerliang , thanks for your attention. I think you changed the codes since it initially cannot generate outputs on the validation set. The reason may be caused by [here](https://github.com/yanx27/JS3C-Net/blob/b0c7a02582efba6ae88107d3b25e93bb83a10aa2/test_kitti_segment.py#L199) and you can simply comment these `if` loop. Since we drop the irrelative labels to calculate IoU, but if you want to use the official tool of benchmark to evaluate or visualize, you need to keep the point's number the same.

**Comment by hackerliang** [comment]
@yanx27 I just comment that [if loop](https://github.com/yanx27/JS3C-Net/blob/b0c7a02582efba6ae88107d3b25e93bb83a10aa2/test_kitti_segment.py#L197)  and everything works as expected.

Thank you for your patient reply!

Best, Liang
